development:
 adapter: postgresql
 encoding: unicode
 database: search_dev
 pool: 5
 username: jhendley25
 password:


test:
 adapter: postgresql
 encoding: unicode
 database: search_test
 pool: 5
 username: jhendley25
 password:
